AllCops:
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes:
    - db/schema.rb
    - db/migrate/*
  RunRailsCops: true

StringLiterals:
  EnforcedStyle: double_quotes

LineLength:
  Max: 150

Documentation:
  Enabled: false